# reports/widget_registry.py
"""
Widget Registry - Defines all available dashboard widgets organized by category.

Categories:
- USERS: User management statistics and activity
- REPORTS: Report and subscription metrics  
- DATABASE: Company database statistics
- ACTIVITY: System activity tracking
- PROJECTS: Data collection projects
- SYSTEM: System health, security, and monitoring

NOTE: Payment/revenue widgets have been removed as payment functionality 
is not yet implemented in this platform.
"""

AVAILABLE_WIDGETS = [
    # =========================================================================
    # USERS WIDGETS - User management and activity (11 widgets)
    # =========================================================================
    {
        'widget_key': 'total_users',
        'title': 'Total Users',
        'description': 'Total number of users in the system',
        'icon': 'users',
        'category': 'USERS',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 1,
    },
    {
        'widget_key': 'total_clients',
        'title': 'Client Users',
        'description': 'Total number of client users',
        'icon': 'user-check',
        'category': 'USERS',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 2,
    },
    {
        'widget_key': 'staff_members',
        'title': 'Staff Members',
        'description': 'Total number of staff and admin users',
        'icon': 'user-cog',
        'category': 'USERS',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 3,
    },
    {
        'widget_key': 'data_collectors',
        'title': 'Data Collectors',
        'description': 'Total number of data collector users',
        'icon': 'clipboard-list',
        'category': 'USERS',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 4,
    },
    {
        'widget_key': 'guest_users',
        'title': 'Guest Users',
        'description': 'Total number of guest users',
        'icon': 'user',
        'category': 'USERS',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 5,
    },
    {
        'widget_key': 'new_users_this_month',
        'title': 'New Users This Month',
        'description': 'Users registered in the last 30 days',
        'icon': 'user-plus',
        'category': 'USERS',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 6,
    },
    {
        'widget_key': 'users_by_role',
        'title': 'Users by Role',
        'description': 'Breakdown of users by their role',
        'icon': 'pie-chart',
        'category': 'USERS',
        'width': 2,
        'height': 1,
        'is_enabled': True,
        'display_order': 7,
    },
    {
        'widget_key': 'most_active_users',
        'title': 'Most Active Users',
        'description': 'Top users by login frequency',
        'icon': 'trending-up',
        'category': 'USERS',
        'width': 2,
        'height': 1,
        'is_enabled': True,
        'display_order': 8,
    },
    {
        'widget_key': 'online_users',
        'title': 'Online Users',
        'description': 'Users currently logged in',
        'icon': 'wifi',
        'category': 'USERS',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 9,
    },
    {
        'widget_key': 'new_registrations',
        'title': 'New Registrations',
        'description': 'User signup trends',
        'icon': 'user-plus',
        'category': 'USERS',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 10,
    },
    {
        'widget_key': 'inactive_users',
        'title': 'Inactive Users',
        'description': 'Users not logged in recently',
        'icon': 'user-x',
        'category': 'USERS',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 11,
    },

    # =========================================================================
    # REPORTS WIDGETS - Report and subscription metrics
    # =========================================================================
    {
        'widget_key': 'total_reports',
        'title': 'Total Reports',
        'description': 'Total number of reports in the system',
        'icon': 'file-bar-chart',
        'category': 'REPORTS',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 20,
    },
    {
        'widget_key': 'custom_reports',
        'title': 'Custom Reports',
        'description': 'Total number of custom reports created',
        'icon': 'file-text',
        'category': 'REPORTS',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 21,
    },
    {
        'widget_key': 'active_subscriptions',
        'title': 'Active Subscriptions',
        'description': 'Number of currently active report subscriptions',
        'icon': 'check-circle',
        'category': 'REPORTS',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 22,
    },
    {
        'widget_key': 'total_subscriptions',
        'title': 'Total Subscriptions',
        'description': 'Total subscriptions (all statuses)',
        'icon': 'layers',
        'category': 'REPORTS',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 23,
    },
    {
        'widget_key': 'pending_subscriptions',
        'title': 'Pending Subscriptions',
        'description': 'Subscriptions awaiting activation',
        'icon': 'clock',
        'category': 'REPORTS',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 24,
    },
    {
        'widget_key': 'subscription_expiry',
        'title': 'Expiring Soon',
        'description': 'Subscriptions expiring in the next 30 days',
        'icon': 'calendar-clock',
        'category': 'REPORTS',
        'width': 2,
        'height': 1,
        'is_enabled': True,
        'display_order': 25,
    },
    {
        'widget_key': 'reports_by_category',
        'title': 'Reports by Category',
        'description': 'Distribution of reports across categories',
        'icon': 'bar-chart-3',
        'category': 'REPORTS',
        'width': 2,
        'height': 1,
        'is_enabled': False,
        'display_order': 26,
    },

    # =========================================================================
    # DATABASE WIDGETS - Company database statistics
    # =========================================================================
    {
        'widget_key': 'total_companies',
        'title': 'Total Companies',
        'description': 'Total number of companies in the database',
        'icon': 'building-2',
        'category': 'DATABASE',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 30,
    },
    {
        'widget_key': 'total_records',
        'title': 'Total Records',
        'description': 'Total number of records in the database',
        'icon': 'database',
        'category': 'DATABASE',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 31,
    },
    {
        'widget_key': 'total_production_sites',
        'title': 'Production Sites',
        'description': 'Total number of production sites across all companies',
        'icon': 'factory',
        'category': 'DATABASE',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 32,
    },
    {
        'widget_key': 'companies_by_status',
        'title': 'Companies by Status',
        'description': 'Complete, Incomplete, and Deleted companies',
        'icon': 'chart-pie',
        'category': 'DATABASE',
        'width': 2,
        'height': 1,
        'is_enabled': True,
        'display_order': 33,
    },
    {
        'widget_key': 'records_by_category',
        'title': 'Sites by Category',
        'description': 'Production sites breakdown by category',
        'icon': 'pie-chart',
        'category': 'DATABASE',
        'width': 2,
        'height': 1,
        'is_enabled': True,
        'display_order': 34,
    },
    {
        'widget_key': 'top_countries',
        'title': 'Top Countries',
        'description': 'Countries with the most companies',
        'icon': 'globe',
        'category': 'DATABASE',
        'width': 2,
        'height': 1,
        'is_enabled': True,
        'display_order': 35,
    },
    {
        'widget_key': 'multi_category_companies',
        'title': 'Multi-Category Companies',
        'description': 'Companies operating in multiple categories',
        'icon': 'layers',
        'category': 'DATABASE',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 36,
    },
    {
        'widget_key': 'new_companies_this_month',
        'title': 'New This Month',
        'description': 'Companies added in the last 30 days',
        'icon': 'building-plus',
        'category': 'DATABASE',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 37,
    },
    {
        'widget_key': 'top_materials',
        'title': 'Top Materials',
        'description': 'Most commonly used polymer materials',
        'icon': 'package',
        'category': 'DATABASE',
        'width': 2,
        'height': 1,
        'is_enabled': True,
        'display_order': 38,
    },
    {
        'widget_key': 'monthly_trend',
        'title': 'Monthly Trend',
        'description': 'Company additions over time',
        'icon': 'trending-up',
        'category': 'DATABASE',
        'width': 2,
        'height': 1,
        'is_enabled': True,
        'display_order': 39,
    },
    {
        'widget_key': 'top_regions',
        'title': 'Top Regions',
        'description': 'Regions with the most companies',
        'icon': 'map-pin',
        'category': 'DATABASE',
        'width': 2,
        'height': 1,
        'is_enabled': False,
        'display_order': 40,
    },

    # =========================================================================
    # ACTIVITY WIDGETS - System activity tracking
    # =========================================================================
    {
        'widget_key': 'recent_activity',
        'title': 'Recent Activity',
        'description': 'Latest system activities',
        'icon': 'activity',
        'category': 'ACTIVITY',
        'width': 2,
        'height': 1,
        'is_enabled': True,
        'display_order': 50,
    },
    {
        'widget_key': 'activity_feed',
        'title': 'Activity Feed',
        'description': 'Real-time activity stream',
        'icon': 'rss',
        'category': 'ACTIVITY',
        'width': 2,
        'height': 2,
        'is_enabled': True,
        'display_order': 51,
    },
    {
        'widget_key': 'recent_logins',
        'title': 'Recent Logins',
        'description': 'Latest user login activity',
        'icon': 'log-in',
        'category': 'ACTIVITY',
        'width': 2,
        'height': 1,
        'is_enabled': True,
        'display_order': 52,
    },
    {
        'widget_key': 'user_activity_timeline',
        'title': 'User Activity',
        'description': 'Recent user actions timeline',
        'icon': 'activity',
        'category': 'ACTIVITY',
        'width': 2,
        'height': 1,
        'is_enabled': True,
        'display_order': 53,
    },
    {
        'widget_key': 'login_activity_trend',
        'title': 'Login Activity Trend',
        'description': 'Daily login patterns over time',
        'icon': 'bar-chart-2',
        'category': 'ACTIVITY',
        'width': 2,
        'height': 1,
        'is_enabled': True,
        'display_order': 54,
    },
    {
        'widget_key': 'activity_heatmap',
        'title': 'Activity Heatmap',
        'description': 'User activity patterns over time',
        'icon': 'grid-3x3',
        'category': 'ACTIVITY',
        'width': 2,
        'height': 2,
        'is_enabled': False,
        'display_order': 55,
    },

    # =========================================================================
    # PROJECTS WIDGETS - Data collection projects
    # =========================================================================
    {
        'widget_key': 'active_projects',
        'title': 'Active Projects',
        'description': 'Currently active data collection projects',
        'icon': 'folder-open',
        'category': 'PROJECTS',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 60,
    },
    {
        'widget_key': 'total_projects',
        'title': 'Total Projects',
        'description': 'All data collection projects',
        'icon': 'folders',
        'category': 'PROJECTS',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 61,
    },
    {
        'widget_key': 'unverified_sites_pending',
        'title': 'Sites Pending',
        'description': 'Unverified sites awaiting review',
        'icon': 'file-question',
        'category': 'PROJECTS',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 62,
    },
    {
        'widget_key': 'verification_queue',
        'title': 'Verification Queue',
        'description': 'Sites queued for verification',
        'icon': 'list-checks',
        'category': 'PROJECTS',
        'width': 2,
        'height': 1,
        'is_enabled': True,
        'display_order': 63,
    },
    {
        'widget_key': 'sites_by_project',
        'title': 'Sites by Project',
        'description': 'Distribution of sites across projects',
        'icon': 'git-branch',
        'category': 'PROJECTS',
        'width': 2,
        'height': 1,
        'is_enabled': False,
        'display_order': 64,
    },

    # =========================================================================
    # SYSTEM WIDGETS - System health, security, and monitoring (19 widgets)
    # =========================================================================
    # --- Health & Infrastructure ---
    {
        'widget_key': 'system_health',
        'title': 'System Health',
        'description': 'Overall system status and health',
        'icon': 'heart-pulse',
        'category': 'SYSTEM',
        'width': 2,
        'height': 1,
        'is_enabled': True,
        'display_order': 70,
    },
    {
        'widget_key': 'system_resources',
        'title': 'System Resources',
        'description': 'CPU, RAM, and disk usage',
        'icon': 'cpu',
        'category': 'SYSTEM',
        'width': 2,
        'height': 1,
        'is_enabled': True,
        'display_order': 71,
    },
    {
        'widget_key': 'database_status',
        'title': 'Database Status',
        'description': 'Database connection and performance',
        'icon': 'database',
        'category': 'SYSTEM',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 72,
    },
    {
        'widget_key': 'cache_status',
        'title': 'Cache Status',
        'description': 'Redis cache health and performance',
        'icon': 'zap',
        'category': 'SYSTEM',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 73,
    },
    {
        'widget_key': 'storage_status',
        'title': 'Storage Status',
        'description': 'File storage usage and availability',
        'icon': 'hard-drive',
        'category': 'SYSTEM',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 74,
    },
    {
        'widget_key': 'background_tasks',
        'title': 'Background Tasks',
        'description': 'Celery/Redis task queue status',
        'icon': 'refresh-cw',
        'category': 'SYSTEM',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 75,
    },
    {
        'widget_key': 'email_service',
        'title': 'Email Service',
        'description': 'SMTP email service status',
        'icon': 'mail',
        'category': 'SYSTEM',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 76,
    },
    # --- Security & Authentication ---
    {
        'widget_key': '2fa_adoption',
        'title': '2FA Adoption',
        'description': 'Two-factor authentication status',
        'icon': 'shield-check',
        'category': 'SYSTEM',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 77,
    },
    {
        'widget_key': 'successful_logins',
        'title': 'Successful Logins',
        'description': 'Successful login count (24h)',
        'icon': 'log-in',
        'category': 'SYSTEM',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 78,
    },
    {
        'widget_key': 'failed_logins_detail',
        'title': 'Failed Logins',
        'description': 'Failed login attempts',
        'icon': 'shield-x',
        'category': 'SYSTEM',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 79,
    },
    {
        'widget_key': 'login_failure_rate',
        'title': 'Login Failure Rate',
        'description': 'Failed vs successful login ratio',
        'icon': 'alert-triangle',
        'category': 'SYSTEM',
        'width': 2,
        'height': 1,
        'is_enabled': True,
        'display_order': 80,
    },
    {
        'widget_key': 'blocked_ips',
        'title': 'Blocked IPs',
        'description': 'Currently blocked IP addresses',
        'icon': 'ban',
        'category': 'SYSTEM',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 81,
    },
    {
        'widget_key': 'suspicious_activity',
        'title': 'Suspicious Activity',
        'description': 'Security alerts and anomalies',
        'icon': 'alert-octagon',
        'category': 'SYSTEM',
        'width': 2,
        'height': 1,
        'is_enabled': True,
        'display_order': 82,
    },
    {
        'widget_key': 'failed_logins_alert',
        'title': 'Failed Logins Alert',
        'description': 'Recent failed login attempts alert',
        'icon': 'shield-alert',
        'category': 'SYSTEM',
        'width': 1,
        'height': 1,
        'is_enabled': False,  # Disabled - use failed_logins_detail instead
        'display_order': 83,
    },
    # --- Sessions & Analytics ---
    {
        'widget_key': 'active_sessions_detail',
        'title': 'Active Sessions',
        'description': 'Currently connected users',
        'icon': 'users',
        'category': 'SYSTEM',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 84,
    },
    {
        'widget_key': 'session_stats',
        'title': 'Session Stats',
        'description': 'User session analytics',
        'icon': 'timer',
        'category': 'SYSTEM',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 85,
    },
    {
        'widget_key': 'device_browser_stats',
        'title': 'Device & Browser',
        'description': 'User access patterns by device',
        'icon': 'monitor',
        'category': 'SYSTEM',
        'width': 2,
        'height': 1,
        'is_enabled': True,
        'display_order': 86,
    },
    {
        'widget_key': 'geographic_distribution',
        'title': 'Geographic Distribution',
        'description': 'User locations by country',
        'icon': 'globe',
        'category': 'SYSTEM',
        'width': 2,
        'height': 1,
        'is_enabled': True,
        'display_order': 87,
    },
    {
        'widget_key': 'pending_verifications_alert',
        'title': 'Pending Verifications',
        'description': 'Sites awaiting verification for 7+ days',
        'icon': 'clock-alert',
        'category': 'SYSTEM',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 88,
    },
]

# Category definitions with display names and icons
WIDGET_CATEGORIES = {
    'USERS': {
        'name': 'Users',
        'description': 'User management and activity',
        'icon': 'users',
        'order': 1,
    },
    'REPORTS': {
        'name': 'Reports',
        'description': 'Report and subscription metrics',
        'icon': 'file-text',
        'order': 2,
    },
    'DATABASE': {
        'name': 'Database',
        'description': 'Company database statistics',
        'icon': 'database',
        'order': 3,
    },
    'ACTIVITY': {
        'name': 'Activity',
        'description': 'System activity tracking',
        'icon': 'activity',
        'order': 4,
    },
    'PROJECTS': {
        'name': 'Projects',
        'description': 'Data collection projects',
        'icon': 'folder-kanban',
        'order': 5,
    },
    'SYSTEM': {
        'name': 'System',
        'description': 'Health, security, and monitoring',
        'icon': 'settings',
        'order': 6,
    },
}
