
"""
Widget Registry - Central place to define all available widgets.
When you add a new widget, just add it here and it will automatically
appear in the widget management system!
"""

AVAILABLE_WIDGETS = [
    {
        'widget_key': 'total_records',
        'title': 'Total Records',
        'description': 'Shows total number of records in the database with monthly growth',
        'icon': 'Database',
        'category': 'OVERVIEW',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 1,
    },
    {
        'widget_key': 'total_clients',
        'title': 'Total Clients',
        'description': 'Shows total number of client accounts with new user count',
        'icon': 'Users',
        'category': 'OVERVIEW',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 2,
    },
    {
        'widget_key': 'custom_reports',
        'title': 'Custom Reports',
        'description': 'Total number of custom reports created',
        'icon': 'FileText',
        'category': 'OVERVIEW',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 3,
    },
    {
        'widget_key': 'active_subscriptions',
        'title': 'Active Subscriptions',
        'description': 'Number of currently active subscriptions',
        'icon': 'TrendingUp',
        'category': 'OVERVIEW',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 4,
    },
    {
        'widget_key': 'recent_activity',
        'title': 'Recent Activity',
        'description': 'Shows records updated in the last 7 days',
        'icon': 'Activity',
        'category': 'ACTIVITY',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 5,
    },
    {
        'widget_key': 'staff_members',
        'title': 'Staff Members',
        'description': 'Total number of staff accounts',
        'icon': 'Users',
        'category': 'OVERVIEW',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 6,
    },
    {
        'widget_key': 'guest_users',
        'title': 'Guest Users',
        'description': 'Total number of guest accounts',
        'icon': 'Calendar',
        'category': 'OVERVIEW',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 7,
    },
    {
        'widget_key': 'records_by_category',
        'title': 'Records by Category',
        'description': 'Bar chart showing distribution of records across categories',
        'icon': 'BarChart3',
        'category': 'ANALYTICS',
        'width': 2,
        'height': 2,
        'is_enabled': True,
        'display_order': 8,
    },
    {
        'widget_key': 'top_countries',
        'title': 'Top 10 Countries',
        'description': 'Horizontal bar chart of countries with most records',
        'icon': 'Globe',
        'category': 'ANALYTICS',
        'width': 2,
        'height': 2,
        'is_enabled': True,
        'display_order': 9,
    },
    {
        'widget_key': 'monthly_trend',
        'title': 'Monthly Trend',
        'description': 'Line chart showing records added over the last 6 months',
        'icon': 'TrendingUp',
        'category': 'ANALYTICS',
        'width': 2,
        'height': 2,
        'is_enabled': True,
        'display_order': 10,
    },
    {
        'widget_key': 'top_materials',
        'title': 'Top Materials',
        'description': 'Pie chart showing most commonly used materials',
        'icon': 'PieChart',
        'category': 'ANALYTICS',
        'width': 2,
        'height': 2,
        'is_enabled': True,
        'display_order': 11,
    },
    {
        'widget_key': 'subscription_expiry',
        'title': 'Subscription Expiry Alert',
        'description': 'Shows subscriptions expiring in the next 7 and 30 days',
        'icon': 'AlertTriangle',
        'category': 'ALERTS',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 12,
    },
    {
        'widget_key': 'activity_feed',
        'title': 'Recent Activity Feed',
        'description': 'Live feed of recent platform activities',
        'icon': 'Activity',
        'category': 'ACTIVITY',
        'width': 2,
        'height': 2,
        'is_enabled': True,
        'display_order': 13,
    },
    {
        'widget_key': 'quick_stats_comparison',
        'title': 'Quick Stats Comparison',
        'description': 'Compares current metrics with previous period',
        'icon': 'TrendingUp',
        'category': 'ANALYTICS',
        'width': 2,
        'height': 1,
        'is_enabled': True,
        'display_order': 14,
    },
    {
        'widget_key': 'popular_searches',
        'title': 'Popular Searches',
        'description': 'Shows most common search filters and queries',
        'icon': 'Search',
        'category': 'ANALYTICS',
        'width': 1,
        'height': 2,
        'is_enabled': True,
        'display_order': 15,
    },
    {
        'widget_key': 'data_quality',
        'title': 'Data Quality Score',
        'description': 'Overall database quality metrics and completeness',
        'icon': 'CheckCircle',
        'category': 'OVERVIEW',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 16,
    },
    {
        'widget_key': 'revenue_analytics',
        'title': 'Revenue Analytics',
        'description': 'Monthly recurring revenue with trends',
        'icon': 'DollarSign',
        'category': 'ANALYTICS',
        'width': 2,
        'height': 2,
        'is_enabled': True,
        'display_order': 17,
    },
    {
        'widget_key': 'activity_heatmap',
        'title': 'Activity Heatmap',
        'description': 'User activity by day and hour',
        'icon': 'Activity',
        'category': 'ANALYTICS',
        'width': 2,
        'height': 2,
        'is_enabled': True,
        'display_order': 18,
    },
    {
        'widget_key': 'subscription_expiry',
        'title': 'Subscription Expiry',
        'description': 'Subscriptions requiring attention',
        'icon': 'AlertTriangle',
        'category': 'ALERTS',
        'width': 1,
        'height': 2,
        'is_enabled': True,
        'display_order': 19,
    },
    {
        'widget_key': 'activity_feed',
        'title': 'Recent Activity Feed',
        'description': 'Latest platform activities',
        'icon': 'Activity',
        'category': 'ACTIVITY',
        'width': 1,
        'height': 2,
        'is_enabled': True,
        'display_order': 20,
    },
]


def get_widget_by_key(widget_key):
    """Get widget definition by key"""
    for widget in AVAILABLE_WIDGETS:
        if widget['widget_key'] == widget_key:
            return widget
    return None


def get_all_widget_keys():
    """Get list of all widget keys"""
    return [w['widget_key'] for w in AVAILABLE_WIDGETS]