# reports/widget_registry.py

AVAILABLE_WIDGETS = [
    # === OVERVIEW WIDGETS ===
    {
        'widget_key': 'total_records',
        'title': 'Total Records',
        'description': 'Total number of records in the database',
        'icon': 'database',
        'category': 'OVERVIEW',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 1,
    },
    {
        'widget_key': 'total_clients',
        'title': 'Total Clients',
        'description': 'Total number of client users',
        'icon': 'users',
        'category': 'OVERVIEW',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 2,
    },
    {
        'widget_key': 'active_subscriptions',
        'title': 'Active Subscriptions',
        'description': 'Number of active subscriptions',
        'icon': 'trending-up',
        'category': 'OVERVIEW',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 3,
    },
    {
        'widget_key': 'custom_reports',
        'title': 'Custom Reports',
        'description': 'Number of custom reports',
        'icon': 'file-text',
        'category': 'OVERVIEW',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 4,
    },
    {
        'widget_key': 'staff_members',
        'title': 'Staff Members',
        'description': 'Total number of staff users',
        'icon': 'users',
        'category': 'OVERVIEW',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 5,
    },
    {
        'widget_key': 'guest_users',
        'title': 'Guest Users',
        'description': 'Total number of guest users',
        'icon': 'user',
        'category': 'OVERVIEW',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 6,
    },

    # === FINANCIAL ANALYTICS ===
    {
        'widget_key': 'subscription_revenue',
        'title': 'Subscription Revenue',
        'description': 'Total revenue from subscriptions',
        'icon': 'dollar-sign',
        'category': 'ANALYTICS',
        'width': 2,
        'height': 1,
        'is_enabled': True,
        'display_order': 10,
    },
    {
        'widget_key': 'revenue_analytics',
        'title': 'Revenue Analytics',
        'description': 'Detailed revenue breakdown',
        'icon': 'bar-chart',
        'category': 'ANALYTICS',
        'width': 2,
        'height': 1,
        'is_enabled': True,
        'display_order': 11,
    },
    {
        'widget_key': 'conversion_rate',
        'title': 'Conversion Rate',
        'description': 'Visitor to customer conversion rate',
        'icon': 'trending-up',
        'category': 'ANALYTICS',
        'width': 2,
        'height': 1,
        'is_enabled': True,
        'display_order': 12,
    },
    {
        'widget_key': 'customer_lifetime_value',
        'title': 'Customer Lifetime Value',
        'description': 'Average customer lifetime value',
        'icon': 'dollar-sign',
        'category': 'ANALYTICS',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 13,
    },
    {
        'widget_key': 'churn_rate',
        'title': 'Churn Rate',
        'description': 'Customer churn rate',
        'icon': 'trending-down',
        'category': 'ANALYTICS',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 14,
    },
    {
        'widget_key': 'growth_rate',
        'title': 'Growth Rate',
        'description': 'Business growth rate',
        'icon': 'trending-up',
        'category': 'ANALYTICS',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 15,
    },

    # === USER ACTIVITY & ENGAGEMENT ===
    {
        'widget_key': 'activity_heatmap',
        'title': 'Activity Heatmap',
        'description': 'User activity visualization',
        'icon': 'activity',
        'category': 'ACTIVITY',
        'width': 2,
        'height': 2,
        'is_enabled': True,
        'display_order': 20,
    },
    {
        'widget_key': 'recent_activity',
        'title': 'Recent Activity',
        'description': 'Latest user activities',
        'icon': 'activity',
        'category': 'ACTIVITY',
        'width': 2,
        'height': 1,
        'is_enabled': True,
        'display_order': 21,
    },
    {
        'widget_key': 'activity_feed',
        'title': 'Activity Feed',
        'description': 'Real-time activity feed',
        'icon': 'rss',
        'category': 'ACTIVITY',
        'width': 2,
        'height': 2,
        'is_enabled': True,
        'display_order': 22,
    },
    {
        'widget_key': 'page_views_analytics',
        'title': 'Page Views',
        'description': 'Page view analytics',
        'icon': 'eye',
        'category': 'ACTIVITY',
        'width': 1,
        'height': 1,
        'is_enabled': False,
        'display_order': 23,
    },
    {
        'widget_key': 'session_duration',
        'title': 'Session Duration',
        'description': 'Average session duration',
        'icon': 'clock',
        'category': 'ACTIVITY',
        'width': 1,
        'height': 1,
        'is_enabled': False,
        'display_order': 24,
    },
    {
        'widget_key': 'search_analytics',
        'title': 'Search Analytics',
        'description': 'Search behavior analytics',
        'icon': 'search',
        'category': 'ACTIVITY',
        'width': 2,
        'height': 1,
        'is_enabled': False,
        'display_order': 25,
    },
    {
        'widget_key': 'device_analytics',
        'title': 'Device Analytics',
        'description': 'Device usage breakdown',
        'icon': 'smartphone',
        'category': 'ACTIVITY',
        'width': 1,
        'height': 1,
        'is_enabled': False,
        'display_order': 26,
    },
    {
        'widget_key': 'traffic_sources',
        'title': 'Traffic Sources',
        'description': 'Traffic source analysis',
        'icon': 'link',
        'category': 'ACTIVITY',
        'width': 2,
        'height': 1,
        'is_enabled': False,
        'display_order': 27,
    },

    # === GEOGRAPHIC ANALYTICS ===
    {
        'widget_key': 'top_countries',
        'title': 'Top Countries',
        'description': 'Top countries by users',
        'icon': 'globe',
        'category': 'ANALYTICS',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 30,
    },
    {
        'widget_key': 'geographic_heatmap',
        'title': 'Geographic Heatmap',
        'description': 'Global user distribution',
        'icon': 'map',
        'category': 'ANALYTICS',
        'width': 2,
        'height': 2,
        'is_enabled': False,
        'display_order': 31,
    },
    {
        'widget_key': 'country_distribution',
        'title': 'Country Distribution',
        'description': 'User distribution by country',
        'icon': 'globe',
        'category': 'ANALYTICS',
        'width': 2,
        'height': 1,
        'is_enabled': False,
        'display_order': 32,
    },
    {
        'widget_key': 'regional_performance',
        'title': 'Regional Performance',
        'description': 'Performance by region',
        'icon': 'map-pin',
        'category': 'ANALYTICS',
        'width': 2,
        'height': 1,
        'is_enabled': False,
        'display_order': 33,
    },
    {
        'widget_key': 'city_breakdown',
        'title': 'City Breakdown',
        'description': 'Top cities by users',
        'icon': 'map-pin',
        'category': 'ANALYTICS',
        'width': 1,
        'height': 1,
        'is_enabled': False,
        'display_order': 34,
    },

    # === OTHER ANALYTICS ===
    {
        'widget_key': 'records_by_category',
        'title': 'Records by Category',
        'description': 'Records breakdown by category',
        'icon': 'pie-chart',
        'category': 'ANALYTICS',
        'width': 2,
        'height': 1,
        'is_enabled': True,
        'display_order': 40,
    },
    {
        'widget_key': 'monthly_trend',
        'title': 'Monthly Trend',
        'description': 'Monthly data trends',
        'icon': 'trending-up',
        'category': 'ANALYTICS',
        'width': 2,
        'height': 1,
        'is_enabled': True,
        'display_order': 41,
    },
    {
        'widget_key': 'top_materials',
        'title': 'Top Materials',
        'description': 'Most popular materials',
        'icon': 'package',
        'category': 'ANALYTICS',
        'width': 1,
        'height': 1,
        'is_enabled': True,
        'display_order': 42,
    },
    {
        'widget_key': 'subscription_expiry',
        'title': 'Subscription Expiry',
        'description': 'Upcoming subscription expirations',
        'icon': 'calendar',
        'category': 'ALERTS',
        'width': 2,
        'height': 1,
        'is_enabled': True,
        'display_order': 50,
    },
]