# Generated by Django 5.2.7 on 2025-12-17 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0029_companycollection_collectionitem_favoritecompany_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyViewedCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_id', models.CharField(help_text='ID of the company record', max_length=50)),
                ('company_name', models.CharField(help_text='Company name for display purposes', max_length=255)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, help_text='Company category', max_length=50, null=True)),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed', to='reports.customreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recently Viewed Company',
                'verbose_name_plural': 'Recently Viewed Companies',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', '-viewed_at'], name='dashboard_r_user_id_13741b_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('FAVORITE_ADDED', 'Added to Favorites'), ('FAVORITE_REMOVED', 'Removed from Favorites'), ('COLLECTION_CREATED', 'Created Collection'), ('COLLECTION_DELETED', 'Deleted Collection'), ('COLLECTION_ITEM_ADDED', 'Added to Collection'), ('COLLECTION_ITEM_REMOVED', 'Removed from Collection'), ('COMPANY_VIEWED', 'Viewed Company'), ('REPORT_VIEWED', 'Viewed Report'), ('NOTE_ADDED', 'Added Note'), ('NOTE_UPDATED', 'Updated Note'), ('EXPORT_CREATED', 'Exported Data')], max_length=30)),
                ('company_name', models.CharField(blank=True, help_text='Name of the company involved', max_length=255, null=True)),
                ('report_title', models.CharField(blank=True, help_text='Title of the report involved', max_length=255, null=True)),
                ('collection_name', models.CharField(blank=True, help_text='Name of the collection involved', max_length=100, null=True)),
                ('report_id', models.UUIDField(blank=True, help_text='UUID of the related report', null=True)),
                ('record_id', models.CharField(blank=True, help_text='ID of the company record', max_length=50, null=True)),
                ('collection_id', models.UUIDField(blank=True, help_text='UUID of the related collection', null=True)),
                ('description', models.TextField(blank=True, help_text='Additional description of the activity', null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='dashboard_u_user_id_5b711f_idx'), models.Index(fields=['activity_type'], name='dashboard_u_activit_a0fab2_idx')],
            },
        ),
    ]
