# Generated by Django 5.2.7 on 2025-12-18 10:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layout_type', models.CharField(choices=[('client', 'Client Portal'), ('data_collector', 'Data Collector'), ('guest', 'Guest Layout'), ('admin', 'Admin Dashboard')], help_text='The layout/role this setting applies to', max_length=20, unique=True)),
                ('default_theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System Preference')], default='system', help_text='Default theme for new users', max_length=10)),
                ('allow_user_toggle', models.BooleanField(default=True, help_text='Allow users to change their theme')),
                ('show_toggle_in_header', models.BooleanField(default=True, help_text='Show theme toggle button in header')),
                ('toggle_variant', models.CharField(choices=[('minimal', 'Minimal (Icon only)'), ('pill', 'Pill (Classic toggle)'), ('scene', 'Scene (Day/Night illustration)'), ('glow', 'Glow (Neon effect)'), ('ios', 'iOS (Apple style)'), ('neumorphic', 'Neumorphic (3D soft)'), ('eclipse', 'Eclipse (Sun/Moon)'), ('neon', 'Neon Border'), ('liquid', 'Liquid (Morphing)'), ('rocker', 'Rocker (Vertical switch)'), ('text', 'Text Slide (Dark/Light label)'), ('bouncy', 'Bouncy (Elastic)')], default='scene', help_text='Style of the theme toggle button', max_length=20)),
                ('sidebar_variant', models.CharField(choices=[('default', 'Default (Current)'), ('glass', 'Glass Morphism'), ('gradient', 'Gradient Flow'), ('minimal', 'Minimal Dark'), ('accent', 'Accent Line'), ('floating', 'Floating Cards')], default='default', help_text='Style of the sidebar navigation', max_length=20)),
                ('remember_user_preference', models.BooleanField(default=True, help_text="Remember user's theme preference across sessions")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Theme Setting',
                'verbose_name_plural': 'Theme Settings',
                'ordering': ['layout_type'],
            },
        ),
    ]
