# Generated by Django 5.2.7 on 2025-12-18 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_themesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTypeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('report', 'New Report'), ('subscription', 'Subscription Updates'), ('message', 'Messages'), ('announcement', 'Announcements'), ('payment', 'Payment'), ('system', 'System Notifications'), ('site_submitted', 'Site Submitted (Staff)'), ('site_approved', 'Site Approved'), ('site_rejected', 'Site Rejected')], max_length=30, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of this notification type')),
                ('icon', models.CharField(default='bell', help_text='Lucide icon name', max_length=50)),
                ('color', models.CharField(default='blue', help_text='Color theme (blue, green, purple, orange, red, etc.)', max_length=20)),
                ('email_enabled', models.BooleanField(default=True, help_text='Send email for this notification type')),
                ('inapp_enabled', models.BooleanField(default=True, help_text='Show in-app notification')),
                ('push_enabled', models.BooleanField(default=False, help_text='Send browser push notification')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('target_roles', models.JSONField(default=list, help_text='List of roles that receive this notification')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this notification type')),
            ],
            options={
                'verbose_name': 'Notification Type Config',
                'verbose_name_plural': 'Notification Type Configs',
                'ordering': ['notification_type'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Master switch for all notifications')),
                ('email_notifications_enabled', models.BooleanField(default=True, help_text='Enable email notifications globally')),
                ('email_from_name', models.CharField(default='Zeugma Platform', help_text='Sender name for emails', max_length=100)),
                ('email_reply_to', models.EmailField(blank=True, help_text='Reply-to email address', max_length=254, null=True)),
                ('email_frequency', models.CharField(choices=[('instant', 'Instant'), ('hourly', 'Hourly Digest'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest'), ('never', 'Never')], default='instant', help_text='Default email delivery frequency', max_length=20)),
                ('include_email_footer', models.BooleanField(default=True, help_text='Include unsubscribe link in emails')),
                ('inapp_notifications_enabled', models.BooleanField(default=True, help_text='Enable in-app notifications')),
                ('notification_sound_enabled', models.BooleanField(default=False, help_text='Play sound for new notifications')),
                ('auto_dismiss_seconds', models.IntegerField(default=0, help_text='Auto-dismiss toast after N seconds (0 = never)')),
                ('max_notifications_shown', models.IntegerField(default=50, help_text='Maximum notifications to keep in history')),
                ('push_notifications_enabled', models.BooleanField(default=False, help_text='Enable browser push notifications')),
                ('daily_summary_enabled', models.BooleanField(default=True, help_text='Send daily summary emails to staff')),
                ('daily_summary_time', models.TimeField(default='09:00', help_text='Time to send daily summary (UTC)')),
                ('allow_user_preferences', models.BooleanField(default=True, help_text='Allow users to customize their notification preferences')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Settings',
                'verbose_name_plural': 'Notification Settings',
            },
        ),
    ]
