# Generated by Django 5.2.7 on 2025-10-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_backup_codes_user_is_2fa_setup_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='backup_codes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='two_factor_secret',
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
