# Generated by Django 5.2.7 on 2025-11-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_last_login_ip_user_login_count_loginhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('STAFF_ADMIN', 'Staff Admin'), ('DATA_COLLECTOR', 'Data Collector'), ('CLIENT', 'Client'), ('GUEST', 'Guest')], default='GUEST', max_length=20),
        ),
    ]
