# Generated by Django 5.2.7 on 2025-12-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_password_changed_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_timesta_40aa9a_idx',
            old_name='accounts_al_time_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_event_t_e6c90a_idx',
            old_name='accounts_al_event_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_user_id_1110c4_idx',
            old_name='accounts_al_user_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_severit_2992a7_idx',
            old_name='accounts_al_sev_idx',
        ),
        migrations.RenameIndex(
            model_name='failedloginattempt',
            new_name='accounts_fa_ip_addr_8a212f_idx',
            old_name='accounts_fa_ip_idx',
        ),
        migrations.RenameIndex(
            model_name='failedloginattempt',
            new_name='accounts_fa_usernam_746227_idx',
            old_name='accounts_fa_user_idx',
        ),
        migrations.AlterField(
            model_name='securitysettings',
            name='email_2fa_enabled',
            field=models.BooleanField(default=True, help_text='Enable email-based 2FA'),
        ),
    ]
