# Generated by Django 5.2.7 on 2025-12-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_email_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailbranding',
            name='primary_color',
            field=models.CharField(default='#8b5cf6', help_text='Primary brand color (hex)', max_length=7),
        ),
        migrations.AlterField(
            model_name='emailbranding',
            name='secondary_color',
            field=models.CharField(default='#7c3aed', help_text='Secondary brand color (hex)', max_length=7),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('welcome', 'Welcome Email'), ('user_invited', 'User Invitation'), ('password_reset', 'Password Reset Request'), ('password_changed', 'Password Changed Confirmation'), ('2fa_code', '2FA Verification Code'), ('2fa_enabled', '2FA Enabled Confirmation'), ('2fa_disabled', '2FA Disabled Notification'), ('new_device_login', 'New Device Login Alert'), ('suspicious_login', 'Suspicious Login Activity'), ('account_locked', 'Account Locked Notification'), ('report_ready', 'Report Ready Notification'), ('announcement_info', 'System Announcement (Info)'), ('announcement_warning', 'System Announcement (Warning)'), ('announcement_success', 'System Announcement (Success)'), ('announcement_urgent', 'System Announcement (Urgent)')], max_length=50, unique=True),
        ),
    ]
