# Generated by Django 5.2.7 on 2025-12-20 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_emailbranding_primary_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAnalyticsIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('measurement_id', models.CharField(blank=True, help_text='GA4 Measurement ID (e.g., G-XXXXXXXXXX)', max_length=50, null=True)),
                ('track_page_views', models.BooleanField(default=True, help_text='Track page views')),
                ('track_report_downloads', models.BooleanField(default=True, help_text='Track report downloads')),
                ('track_search_queries', models.BooleanField(default=True, help_text='Track search queries')),
                ('track_filter_usage', models.BooleanField(default=True, help_text='Track filter usage')),
                ('track_user_actions', models.BooleanField(default=False, help_text='Track user actions (requires consent)')),
                ('anonymize_ip', models.BooleanField(default=True, help_text='Anonymize user IP addresses')),
                ('debug_mode', models.BooleanField(default=False, help_text='Enable debug mode for testing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ga_integration_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Analytics Integration',
                'verbose_name_plural': 'Google Analytics Integration',
            },
        ),
        migrations.CreateModel(
            name='SlackIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('webhook_url', models.URLField(blank=True, help_text='Slack Incoming Webhook URL', null=True)),
                ('channel_name', models.CharField(blank=True, default='#general', help_text='Channel name for display', max_length=100)),
                ('bot_name', models.CharField(blank=True, default='Zeugma Bot', help_text='Bot display name', max_length=100)),
                ('bot_icon', models.CharField(blank=True, default=':robot_face:', help_text='Bot icon emoji', max_length=50)),
                ('notify_user_created', models.BooleanField(default=True, help_text='Notify when new user is created')),
                ('notify_user_invited', models.BooleanField(default=True, help_text='Notify when user is invited')),
                ('notify_user_login', models.BooleanField(default=False, help_text='Notify on user login (high volume)')),
                ('notify_report_published', models.BooleanField(default=True, help_text='Notify when report is published')),
                ('notify_report_updated', models.BooleanField(default=False, help_text='Notify when report is updated')),
                ('notify_data_imported', models.BooleanField(default=True, help_text='Notify when data import completes')),
                ('notify_data_import_failed', models.BooleanField(default=True, help_text='Notify when data import fails')),
                ('notify_security_alerts', models.BooleanField(default=True, help_text='Notify on security events (failed logins, 2FA changes)')),
                ('notify_system_announcements', models.BooleanField(default=True, help_text='Notify on system announcements')),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_success', models.BooleanField(blank=True, null=True)),
                ('last_notification_at', models.DateTimeField(blank=True, null=True)),
                ('notification_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slack_integration_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Slack Integration',
                'verbose_name_plural': 'Slack Integration',
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Webhook name for identification', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('url', models.URLField(help_text='Endpoint URL to send events to')),
                ('secret', models.CharField(blank=True, help_text='Secret for HMAC signature verification', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('failed', 'Failed')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('events', models.JSONField(default=list, help_text='List of event types to subscribe to')),
                ('custom_headers', models.JSONField(blank=True, default=dict, help_text='Custom HTTP headers to include')),
                ('max_retries', models.PositiveIntegerField(default=3, help_text='Max retry attempts on failure')),
                ('retry_delay_seconds', models.PositiveIntegerField(default=60, help_text='Delay between retries')),
                ('timeout_seconds', models.PositiveIntegerField(default=30, help_text='Request timeout')),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('successful_deliveries', models.PositiveIntegerField(default=0)),
                ('failed_deliveries', models.PositiveIntegerField(default=0)),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('last_delivery_success', models.BooleanField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('request_headers', models.JSONField(default=dict)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Request duration in milliseconds', null=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='accounts.webhook')),
            ],
            options={
                'verbose_name': 'Webhook Delivery Log',
                'verbose_name_plural': 'Webhook Delivery Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['webhook', '-created_at'], name='accounts_we_webhook_b2b926_idx'), models.Index(fields=['event_type'], name='accounts_we_event_t_eec300_idx')],
            },
        ),
    ]
