# Generated by Django 5.2.7 on 2025-12-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('user_invited', 'User Creation'), ('2fa_setup_code', 'Two-Factor Authentication Setup'), ('welcome', 'Welcome Email'), ('2fa_disabled', '2FA Disabled Confirmation'), ('2fa_enabled_notification', '2FA Enabled Notification'), ('2fa_enabled', '2FA Enabled Confirmation'), ('password_reset', 'Password Reset Request'), ('password_reset_success', 'Password Reset Confirmation'), ('2fa_code', '2FA Verification Code'), ('password_changed', 'Password Changed Confirmation'), ('account_locked', 'Account Locked Notification'), ('new_device_login', 'New Device Login Alert'), ('suspicious_login', 'Suspicious Login Activity'), ('report_ready', 'Report Ready Notification'), ('announcement_info', 'System Announcement (Info)'), ('announcement_warning', 'System Announcement (Warning)'), ('announcement_success', 'System Announcement (Success)'), ('announcement_urgent', 'System Announcement (Urgent)')], max_length=50, unique=True),
        ),
    ]
