# Generated by Django 5.2.7 on 2025-12-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_defaultusersettings_ui_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultusersettings',
            name='default_header_color_scheme',
            field=models.CharField(choices=[('default', 'Default'), ('dark', 'Dark'), ('midnight', 'Midnight Blue'), ('ocean', 'Ocean'), ('forest', 'Forest'), ('sunset', 'Sunset'), ('lavender', 'Lavender'), ('slate', 'Slate'), ('rose', 'Rose'), ('amber', 'Amber'), ('purple', 'Purple'), ('teal', 'Teal'), ('pink', 'Pink'), ('lime', 'Lime'), ('cyan', 'Cyan'), ('stone', 'Stone')], default='slate', max_length=20),
        ),
        migrations.AlterField(
            model_name='defaultusersettings',
            name='default_sidebar_color_scheme',
            field=models.CharField(choices=[('default', 'Default'), ('dark', 'Dark'), ('midnight', 'Midnight Blue'), ('ocean', 'Ocean'), ('forest', 'Forest'), ('sunset', 'Sunset'), ('lavender', 'Lavender'), ('slate', 'Slate'), ('rose', 'Rose'), ('amber', 'Amber'), ('purple', 'Purple'), ('teal', 'Teal'), ('pink', 'Pink'), ('lime', 'Lime'), ('cyan', 'Cyan'), ('stone', 'Stone')], default='slate', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='header_color_scheme',
            field=models.CharField(choices=[('default', 'Default'), ('dark', 'Dark'), ('midnight', 'Midnight Blue'), ('ocean', 'Ocean'), ('forest', 'Forest'), ('sunset', 'Sunset'), ('lavender', 'Lavender'), ('slate', 'Slate'), ('rose', 'Rose'), ('amber', 'Amber'), ('purple', 'Purple'), ('teal', 'Teal'), ('pink', 'Pink'), ('lime', 'Lime'), ('cyan', 'Cyan'), ('stone', 'Stone')], default='slate', help_text='Color scheme for the header', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='sidebar_color_scheme',
            field=models.CharField(choices=[('default', 'Default'), ('dark', 'Dark'), ('midnight', 'Midnight Blue'), ('ocean', 'Ocean'), ('forest', 'Forest'), ('sunset', 'Sunset'), ('lavender', 'Lavender'), ('slate', 'Slate'), ('rose', 'Rose'), ('amber', 'Amber'), ('purple', 'Purple'), ('teal', 'Teal'), ('pink', 'Pink'), ('lime', 'Lime'), ('cyan', 'Cyan'), ('stone', 'Stone')], default='slate', help_text='Color scheme for the sidebar', max_length=20),
        ),
    ]
