# Generated by Django - Remove daily_summary_email field

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_defaultusersettings_default_header_color_scheme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='daily_summary_email',
        ),
    ]
