# Generated by Django 5.2.7 on 2025-10-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superdatabaserecord',
            name='other_bags',
            field=models.BooleanField(default=False, verbose_name='Other Bags'),
        ),
        migrations.AlterField(
            model_name='superdatabaserecord',
            name='other_sacks',
            field=models.BooleanField(default=False, verbose_name='Other Sacks'),
        ),
    ]
