# Generated by Django 5.2.7 on 2025-10-10 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_superdatabaserecord_other_bags_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_key', models.CharField(help_text="Unique identifier for the widget (e.g., 'subscription_expiry')", max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Lucide icon name (e.g., 'TrendingUp', 'Users')", max_length=50)),
                ('category', models.CharField(choices=[('OVERVIEW', 'Overview'), ('ANALYTICS', 'Analytics'), ('ACTIVITY', 'Activity'), ('ALERTS', 'Alerts'), ('REPORTS', 'Reports')], default='OVERVIEW', max_length=20)),
                ('width', models.IntegerField(default=1, help_text='Width in grid columns (1-4)')),
                ('height', models.IntegerField(default=1, help_text='Height in grid rows (1-3)')),
                ('is_enabled', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Widget-specific settings as JSON')),
                ('required_permission', models.CharField(blank=True, help_text='Permission required to view this widget', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Widget',
                'verbose_name_plural': 'Dashboard Widgets',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserWidgetPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_preferences', to=settings.AUTH_USER_MODEL)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.dashboardwidget')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('user', 'widget')},
            },
        ),
    ]
