# Generated by Django 5.2.7 on 2025-11-10 19:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_unverifiedsite_verificationhistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='unverifiedsite',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('NEEDS_REVISION', 'Needs Revision'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('TRANSFERRED', 'Transferred to Superdatabase')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='DataCollectionProject',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(help_text="E.g., 'Injection Moulders PVC - North Africa Q4 2024'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Project description and scope', null=True)),
                ('category', models.CharField(choices=[('INJECTION', 'Injection Moulders'), ('BLOW', 'Blow Moulders'), ('ROTO', 'Roto Moulders'), ('PE_FILM', 'PE Film Extruders'), ('SHEET', 'Sheet Extruders'), ('PIPE', 'Pipe Extruders'), ('TUBE_HOSE', 'Tube & Hose Extruders'), ('PROFILE', 'Profile Extruders'), ('CABLE', 'Cable Extruders'), ('COMPOUNDER', 'Compounders')], help_text='Primary category for this project', max_length=50)),
                ('target_region', models.CharField(blank=True, help_text="Target region (e.g., 'North Africa', 'Europe', 'Asia')", max_length=255, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('target_count', models.IntegerField(default=0, help_text='Target number of companies to collect')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, help_text='Target completion date', null=True)),
                ('assigned_reviewers', models.ManyToManyField(blank=True, help_text='Staff/Super admins assigned to review this project', limit_choices_to={'role__in': ['SUPERADMIN', 'STAFF_ADMIN']}, related_name='assigned_review_projects', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='Data collector who created this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Collection Project',
                'verbose_name_plural': 'Data Collection Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project this site belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unverified_sites', to='reports.datacollectionproject'),
        ),
        migrations.CreateModel(
            name='ProjectActivityLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'Project Created'), ('UPDATED', 'Project Updated'), ('SITE_ADDED', 'Site Added'), ('SITE_REMOVED', 'Site Removed'), ('BULK_APPROVED', 'Bulk Approved'), ('BULK_REJECTED', 'Bulk Rejected'), ('BULK_TRANSFERRED', 'Bulk Transferred'), ('REVIEWER_ASSIGNED', 'Reviewer Assigned'), ('STATUS_CHANGED', 'Status Changed'), ('COMPLETED', 'Project Completed')], max_length=100)),
                ('description', models.TextField(blank=True, help_text='Additional details about the action', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_activities', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='reports.datacollectionproject')),
            ],
            options={
                'verbose_name': 'Project Activity Log',
                'verbose_name_plural': 'Project Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReviewNote',
            fields=[
                ('note_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_text', models.TextField(help_text='Review note or feedback')),
                ('is_internal', models.BooleanField(default=False, help_text='Internal staff notes (not visible to data collectors)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, help_text='Optional attachment', null=True, upload_to='review_notes/')),
                ('created_by', models.ForeignKey(help_text='User who created this note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_review_notes', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(help_text='The unverified site this note is about', on_delete=django.db.models.deletion.CASCADE, related_name='review_notes', to='reports.unverifiedsite')),
            ],
            options={
                'verbose_name': 'Review Note',
                'verbose_name_plural': 'Review Notes',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='datacollectionproject',
            index=models.Index(fields=['status', '-created_at'], name='reports_dat_status_763a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='datacollectionproject',
            index=models.Index(fields=['created_by', '-created_at'], name='reports_dat_created_af2c09_idx'),
        ),
        migrations.AddIndex(
            model_name='datacollectionproject',
            index=models.Index(fields=['category'], name='reports_dat_categor_e712ed_idx'),
        ),
        migrations.AddIndex(
            model_name='projectactivitylog',
            index=models.Index(fields=['project', '-timestamp'], name='reports_pro_project_3c81c2_idx'),
        ),
        migrations.AddIndex(
            model_name='projectactivitylog',
            index=models.Index(fields=['performed_by', '-timestamp'], name='reports_pro_perform_25c97b_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewnote',
            index=models.Index(fields=['site', 'created_at'], name='reports_rev_site_id_b88ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewnote',
            index=models.Index(fields=['created_by', '-created_at'], name='reports_rev_created_08afa9_idx'),
        ),
    ]
