# Generated by Django 5.2.7 on 2025-11-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_unverifiedsite_verification_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unverifiedsite',
            name='data_quality_score',
            field=models.FloatField(default=0.0),
        ),
    ]
