# Generated by Django 5.2.7 on 2025-11-16 22:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_unverifiedsite_data_quality_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unverifiedsite',
            name='calling_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('YELLOW', 'Needs Alternative Numbers'), ('RED', 'Not Relevant / Never Picked Up'), ('PURPLE', 'Language Barrier'), ('BLUE', 'Call Back Later'), ('GREEN', 'Complete - Ready for Review')], default='NOT_STARTED', help_text='Current status in the calling workflow', max_length=20, verbose_name='Calling Status'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='calling_status_changed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when calling status was last changed', null=True, verbose_name='Calling Status Changed At'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='calling_status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calling_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Calling Status Changed By'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='is_pre_filled',
            field=models.BooleanField(default=False, help_text='True if this site was created by admin with initial data', verbose_name='Has Pre-filled Data'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='pre_filled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pre-filled At'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='pre_filled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_filled_sites', to=settings.AUTH_USER_MODEL, verbose_name='Pre-filled By'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='total_calls',
            field=models.IntegerField(default=0, help_text='Number of call attempts made', verbose_name='Total Calls Made'),
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('call_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Call ID')),
                ('call_number', models.IntegerField(help_text='Sequential number of this call (1, 2, 3, etc.)', verbose_name='Call Number')),
                ('call_timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the call was made', verbose_name='Call Timestamp')),
                ('call_notes', models.TextField(blank=True, help_text='Notes about this specific call (e.g., "No answer", "Spoke with receptionist")', verbose_name='Call Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='reports.unverifiedsite', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Call Log',
                'verbose_name_plural': 'Call Logs',
                'ordering': ['call_number'],
                'indexes': [models.Index(fields=['site', 'call_number'], name='reports_cal_site_id_222c83_idx'), models.Index(fields=['site', '-call_timestamp'], name='reports_cal_site_id_cf8be5_idx')],
                'unique_together': {('site', 'call_number')},
            },
        ),
        migrations.CreateModel(
            name='FieldConfirmation',
            fields=[
                ('confirmation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Confirmation ID')),
                ('field_name', models.CharField(help_text='Name of the field (e.g., "company_name", "phone_number")', max_length=100, verbose_name='Field Name')),
                ('is_confirmed', models.BooleanField(default=False, help_text='True if data collector confirmed this field', verbose_name='Is Confirmed')),
                ('is_new_data', models.BooleanField(default=False, help_text='True if data collector added new information', verbose_name='Is New Data')),
                ('is_pre_filled', models.BooleanField(default=False, help_text='True if this field was pre-filled by admin', verbose_name='Is Pre-filled')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed At')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this field confirmation', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_confirmations', to=settings.AUTH_USER_MODEL, verbose_name='Confirmed By')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_confirmations', to='reports.unverifiedsite', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Field Confirmation',
                'verbose_name_plural': 'Field Confirmations',
                'indexes': [models.Index(fields=['site', 'field_name'], name='reports_fie_site_id_d33212_idx'), models.Index(fields=['site', 'is_confirmed'], name='reports_fie_site_id_cc9ff4_idx')],
                'unique_together': {('site', 'field_name')},
            },
        ),
    ]
