# Generated by Django 5.2.7 on 2025-11-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_unverifiedsite_calling_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldconfirmation',
            name='last_selected',
            field=models.CharField(blank=True, choices=[('is_pre_filled', 'Pre-filled'), ('is_confirmed', 'Confirmed'), ('is_new_data', 'New Data')], help_text='Tracks which confirmation type was last selected for color coding', max_length=20, null=True, verbose_name='Last Selected'),
        ),
    ]
