# Generated by Django 5.2.7 on 2025-11-18 11:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_fieldconfirmation_last_selected'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallingStatusHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('status_notes', models.TextField(blank=True, help_text='Notes about why status was changed')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_history_changes', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='reports.unverifiedsite')),
            ],
            options={
                'verbose_name': 'Calling Status History',
                'verbose_name_plural': 'Calling Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
