# Generated by Django 5.2.7 on 2025-11-19 19:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_callingstatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyResearchResult',
            fields=[
                ('research_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Research ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name Searched')),
                ('country', models.CharField(max_length=100, verbose_name='Country Searched')),
                ('result_data', models.JSONField(help_text='Full JSON data returned from AI research', verbose_name='Research Result Data')),
                ('model_used', models.CharField(blank=True, max_length=100, null=True, verbose_name='AI Model Used')),
                ('searched_at', models.DateTimeField(auto_now_add=True, verbose_name='Search Date/Time')),
                ('official_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Official Company Name')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('industry', models.CharField(blank=True, max_length=200, null=True, verbose_name='Industry')),
                ('website', models.URLField(blank=True, max_length=500, null=True, verbose_name='Website')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Marked as Favorite')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='User Notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_results', to=settings.AUTH_USER_MODEL, verbose_name='Researcher')),
            ],
            options={
                'verbose_name': 'Company Research Result',
                'verbose_name_plural': 'Company Research Results',
                'ordering': ['-searched_at'],
                'indexes': [models.Index(fields=['user', '-searched_at'], name='reports_com_user_id_01d3d9_idx'), models.Index(fields=['company_name', 'country'], name='reports_com_company_8f693f_idx'), models.Index(fields=['is_favorite'], name='reports_com_is_favo_c195e2_idx')],
            },
        ),
    ]
