# Generated by Django 5.2.7 on 2025-11-20 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_companyresearchresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollectionproject',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Data collector assigned to work on this project', limit_choices_to={'role': 'DATA_COLLECTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
