# Generated by Django 5.2.7 on 2025-11-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_datacollectionproject_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationhistory',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('MODIFIED', 'Modified'), ('ASSIGNED', 'Assigned'), ('TRANSFERRED', 'Transferred to Superdatabase'), ('COMMENT_ADDED', 'Comment Added'), ('NEEDS_REVISION', 'Needs Revision'), ('UNDER_REVIEW', 'Under Review')], max_length=20),
        ),
    ]
