# Generated by Django 5.2.7 on 2025-11-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_company_centric_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionsiteversion',
            name='company_data_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of company info at version creation time'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='contact_data_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of contact info at version creation time'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='notes_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='Snapshot of notes at version creation time'),
        ),
    ]
