# Generated by Django 5.2.7 on 2025-11-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_productionsiteversion_company_data_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionsiteversion',
            name='is_initial',
            field=models.BooleanField(default=False, help_text='True if this is the Initial Version (baseline snapshot, cannot be deleted)'),
        ),
    ]
