# Generated by Django 5.2.7 on 2025-11-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_productionsiteversion_is_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionsiteversion',
            name='technical_data_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of technical fields at version creation time'),
        ),
    ]
