# Generated by Django 5.2.7 on 2025-12-04 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_add_project_code_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionsite',
            name='source_project',
            field=models.ForeignKey(blank=True, help_text='Original project this production site was transferred from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_production_sites', to='reports.datacollectionproject'),
        ),
    ]
