# Generated by Django 5.2.7 on 2025-12-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_customreport_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='hide_contact_persons',
            field=models.BooleanField(default=False, help_text='If checked, contact person information will not be displayed (GDPR compliance)', verbose_name='Hide Contact Persons (GDPR)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'Complete Site (Verified by telephone interview)'), ('INCOMPLETE', 'Incomplete Site (Unverified, estimated data)'), ('DELETED', 'Deleted Site (No data, kept for future reference)'), ('NONE', 'None (No status assigned)')], db_index=True, default='INCOMPLETE', help_text='Current status of the company record', max_length=20),
        ),
        migrations.AlterField(
            model_name='customreport',
            name='source_type',
            field=models.CharField(choices=[('COMPANY_DATABASE', 'Company Database')], default='COMPANY_DATABASE', help_text='Which database this report queries from', max_length=20),
        ),
    ]
