# Generated by Django 5.2.7 on 2025-12-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_company_hide_contact_persons_alter_company_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionsiteversion',
            name='agglomerate_crumbs',
            field=models.BooleanField(default=False, verbose_name='Agglomerate/Crumbs'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='agricultural_chemical_containers',
            field=models.BooleanField(default=False, verbose_name='Agricultural Chemical Containers'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='agricultural_plant_containers',
            field=models.BooleanField(default=False, verbose_name='Agricultural Plant Containers'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='agricultural_source',
            field=models.BooleanField(default=False, verbose_name='Agricultural Source'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='asa',
            field=models.BooleanField(default=False, verbose_name='ASA'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='automotive_battery',
            field=models.BooleanField(default=False, verbose_name='Automotive/Battery'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='automotive_bumper',
            field=models.BooleanField(default=False, verbose_name='Automotive/Bumper'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='automotive_cable',
            field=models.BooleanField(default=False, verbose_name='Automotive/Cable'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='automotive_elv',
            field=models.BooleanField(default=False, verbose_name='Automotive ELV'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='automotive_fuel_tank',
            field=models.BooleanField(default=False, verbose_name='Automotive/Fuel Tank'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='automotive_interior_trim',
            field=models.BooleanField(default=False, verbose_name='Automotive/Interior Trim'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='bottles',
            field=models.BooleanField(default=False, verbose_name='Bottles'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='building_pipe',
            field=models.BooleanField(default=False, verbose_name='Building Pipe'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='clean',
            field=models.BooleanField(default=False, verbose_name='Clean'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='collection_service',
            field=models.BooleanField(default=False, verbose_name='Collection Service'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='commercial_source',
            field=models.BooleanField(default=False, verbose_name='Commercial Source'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='dirty_soiled',
            field=models.BooleanField(default=False, verbose_name='Dirty/Soiled'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='drum_crate_box',
            field=models.BooleanField(default=False, verbose_name='Drum/Crate/Box'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='eps_packaging',
            field=models.BooleanField(default=False, verbose_name='EPS Packaging'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='feedstock_chemical_recycling',
            field=models.BooleanField(default=False, verbose_name='Feedstock/Chemical Recycling'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='filled_compounds',
            field=models.BooleanField(default=False, verbose_name='Filled Compounds'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='finished_products',
            field=models.CharField(blank=True, max_length=255, verbose_name='Finished Products'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='food_grade',
            field=models.BooleanField(default=False, verbose_name='Food Grade'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='food_trays_containers',
            field=models.BooleanField(default=False, verbose_name='Food Trays Containers'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='hazardous',
            field=models.BooleanField(default=False, verbose_name='Hazardous'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='house_municipal_source',
            field=models.BooleanField(default=False, verbose_name='House Municipal Source'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='industrial_source',
            field=models.BooleanField(default=False, verbose_name='Industrial Source'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='main_source',
            field=models.TextField(blank=True, verbose_name='Main Source'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='maximum_capacity',
            field=models.CharField(blank=True, max_length=255, verbose_name='Maximum Capacity'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='metal_detection',
            field=models.BooleanField(default=False, verbose_name='Metal Detection'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='minimum_volume_waste_accepted',
            field=models.CharField(blank=True, max_length=255, verbose_name='Minimum Volume Waste Accepted'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='number_of_recycling_lines',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Recycling Lines'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='other_automotive',
            field=models.CharField(blank=True, max_length=255, verbose_name='Other Automotive'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='other_building',
            field=models.CharField(blank=True, max_length=255, verbose_name='Other Building'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='other_contaminations',
            field=models.CharField(blank=True, max_length=255, verbose_name='Other Contaminations'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='other_markets',
            field=models.TextField(blank=True, verbose_name='Other Markets'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='other_mechanical_process',
            field=models.TextField(blank=True, verbose_name='Other Mechanical Process'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='other_moulded_parts',
            field=models.BooleanField(default=False, verbose_name='Other Moulded Parts'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='other_packaging',
            field=models.CharField(blank=True, max_length=255, verbose_name='Other Packaging'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='other_weee',
            field=models.CharField(blank=True, max_length=255, verbose_name='Other WEEE'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='packaging_film',
            field=models.BooleanField(default=False, verbose_name='Packaging Film'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='pelletising',
            field=models.BooleanField(default=False, verbose_name='Pelletising'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='pellets',
            field=models.BooleanField(default=False, verbose_name='Pellets'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='prewash',
            field=models.BooleanField(default=False, verbose_name='Prewash'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='pur',
            field=models.BooleanField(default=False, verbose_name='PUR'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='pvc_building_profiles',
            field=models.BooleanField(default=False, verbose_name='PVC Building Profiles'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='recycle_non_elv',
            field=models.BooleanField(default=False, verbose_name='Recycle Non ELV'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='recycle_non_weee',
            field=models.BooleanField(default=False, verbose_name='Recycle Non WEEE'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='regrind',
            field=models.BooleanField(default=False, verbose_name='Regrind'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='separation',
            field=models.BooleanField(default=False, verbose_name='Separation'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='single_screws',
            field=models.IntegerField(blank=True, null=True, verbose_name='Single Screws'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='size_reduction',
            field=models.BooleanField(default=False, verbose_name='Size Reduction'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='sorting',
            field=models.BooleanField(default=False, verbose_name='Sorting'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='textile_fibre_filament',
            field=models.BooleanField(default=False, verbose_name='Textile/Fibre Filament'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='textile_non_woven',
            field=models.BooleanField(default=False, verbose_name='Textile/Non Woven'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='textile_woven',
            field=models.BooleanField(default=False, verbose_name='Textile/Woven'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='toys_sports_leisure',
            field=models.BooleanField(default=False, verbose_name='Toys/Sports/Leisure'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='twin_screws',
            field=models.IntegerField(blank=True, null=True, verbose_name='Twin Screws'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='volume_of_recycled_product',
            field=models.CharField(blank=True, max_length=255, verbose_name='Volume of Recycled Product'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='washing',
            field=models.BooleanField(default=False, verbose_name='Washing'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='weee',
            field=models.BooleanField(default=False, verbose_name='WEEE'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='weee_it_electronic',
            field=models.BooleanField(default=False, verbose_name='WEEE IT Electronic'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='weee_large_appliance',
            field=models.BooleanField(default=False, verbose_name='WEEE Large Appliance'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='weee_small_appliance',
            field=models.BooleanField(default=False, verbose_name='WEEE Small Appliance'),
        ),
        migrations.AddField(
            model_name='productionsiteversion',
            name='wet_damp',
            field=models.BooleanField(default=False, verbose_name='Wet/Damp'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='agglomerate_crumbs',
            field=models.BooleanField(default=False, verbose_name='Agglomerate/Crumbs'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='agricultural_chemical_containers',
            field=models.BooleanField(default=False, verbose_name='Agricultural Chemical Containers'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='agricultural_plant_containers',
            field=models.BooleanField(default=False, verbose_name='Agricultural Plant Containers'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='agricultural_source',
            field=models.BooleanField(default=False, verbose_name='Agricultural Source'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='asa',
            field=models.BooleanField(default=False, verbose_name='ASA'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='automotive_battery',
            field=models.BooleanField(default=False, verbose_name='Automotive/Battery'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='automotive_bumper',
            field=models.BooleanField(default=False, verbose_name='Automotive/Bumper'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='automotive_cable',
            field=models.BooleanField(default=False, verbose_name='Automotive/Cable'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='automotive_elv',
            field=models.BooleanField(default=False, verbose_name='Automotive ELV'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='automotive_fuel_tank',
            field=models.BooleanField(default=False, verbose_name='Automotive/Fuel Tank'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='automotive_interior_trim',
            field=models.BooleanField(default=False, verbose_name='Automotive/Interior Trim'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='bottles',
            field=models.BooleanField(default=False, verbose_name='Bottles'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='building_pipe',
            field=models.BooleanField(default=False, verbose_name='Building Pipe'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='clean',
            field=models.BooleanField(default=False, verbose_name='Clean'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='collection_service',
            field=models.BooleanField(default=False, verbose_name='Collection Service'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='commercial_source',
            field=models.BooleanField(default=False, verbose_name='Commercial Source'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='dirty_soiled',
            field=models.BooleanField(default=False, verbose_name='Dirty/Soiled'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='drum_crate_box',
            field=models.BooleanField(default=False, verbose_name='Drum/Crate/Box'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='eps_packaging',
            field=models.BooleanField(default=False, verbose_name='EPS Packaging'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='feedstock_chemical_recycling',
            field=models.BooleanField(default=False, verbose_name='Feedstock/Chemical Recycling'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='filled_compounds',
            field=models.BooleanField(default=False, verbose_name='Filled Compounds'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='finished_products',
            field=models.CharField(blank=True, max_length=255, verbose_name='Finished Products'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='food_grade',
            field=models.BooleanField(default=False, verbose_name='Food Grade'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='food_trays_containers',
            field=models.BooleanField(default=False, verbose_name='Food Trays Containers'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='hazardous',
            field=models.BooleanField(default=False, verbose_name='Hazardous'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='house_municipal_source',
            field=models.BooleanField(default=False, verbose_name='House Municipal Source'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='industrial_source',
            field=models.BooleanField(default=False, verbose_name='Industrial Source'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='main_source',
            field=models.TextField(blank=True, verbose_name='Main Source'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='maximum_capacity',
            field=models.CharField(blank=True, max_length=255, verbose_name='Maximum Capacity'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='metal_detection',
            field=models.BooleanField(default=False, verbose_name='Metal Detection'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='minimum_volume_waste_accepted',
            field=models.CharField(blank=True, max_length=255, verbose_name='Minimum Volume Waste Accepted'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='number_of_recycling_lines',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Recycling Lines'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='other_automotive',
            field=models.CharField(blank=True, max_length=255, verbose_name='Other Automotive'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='other_building',
            field=models.CharField(blank=True, max_length=255, verbose_name='Other Building'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='other_contaminations',
            field=models.CharField(blank=True, max_length=255, verbose_name='Other Contaminations'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='other_markets',
            field=models.TextField(blank=True, verbose_name='Other Markets'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='other_mechanical_process',
            field=models.TextField(blank=True, verbose_name='Other Mechanical Process'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='other_moulded_parts',
            field=models.BooleanField(default=False, verbose_name='Other Moulded Parts'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='other_packaging',
            field=models.CharField(blank=True, max_length=255, verbose_name='Other Packaging'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='other_weee',
            field=models.CharField(blank=True, max_length=255, verbose_name='Other WEEE'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='packaging_film',
            field=models.BooleanField(default=False, verbose_name='Packaging Film'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='pelletising',
            field=models.BooleanField(default=False, verbose_name='Pelletising'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='pellets',
            field=models.BooleanField(default=False, verbose_name='Pellets'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='prewash',
            field=models.BooleanField(default=False, verbose_name='Prewash'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='pur',
            field=models.BooleanField(default=False, verbose_name='PUR'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='pvc_building_profiles',
            field=models.BooleanField(default=False, verbose_name='PVC Building Profiles'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='recycle_non_elv',
            field=models.BooleanField(default=False, verbose_name='Recycle Non ELV'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='recycle_non_weee',
            field=models.BooleanField(default=False, verbose_name='Recycle Non WEEE'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='regrind',
            field=models.BooleanField(default=False, verbose_name='Regrind'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='separation',
            field=models.BooleanField(default=False, verbose_name='Separation'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='single_screws',
            field=models.IntegerField(blank=True, null=True, verbose_name='Single Screws'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='size_reduction',
            field=models.BooleanField(default=False, verbose_name='Size Reduction'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='sorting',
            field=models.BooleanField(default=False, verbose_name='Sorting'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='textile_fibre_filament',
            field=models.BooleanField(default=False, verbose_name='Textile/Fibre Filament'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='textile_non_woven',
            field=models.BooleanField(default=False, verbose_name='Textile/Non Woven'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='textile_woven',
            field=models.BooleanField(default=False, verbose_name='Textile/Woven'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='toys_sports_leisure',
            field=models.BooleanField(default=False, verbose_name='Toys/Sports/Leisure'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='twin_screws',
            field=models.IntegerField(blank=True, null=True, verbose_name='Twin Screws'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='volume_of_recycled_product',
            field=models.CharField(blank=True, max_length=255, verbose_name='Volume of Recycled Product'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='washing',
            field=models.BooleanField(default=False, verbose_name='Washing'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='weee',
            field=models.BooleanField(default=False, verbose_name='WEEE'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='weee_it_electronic',
            field=models.BooleanField(default=False, verbose_name='WEEE IT Electronic'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='weee_large_appliance',
            field=models.BooleanField(default=False, verbose_name='WEEE Large Appliance'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='weee_small_appliance',
            field=models.BooleanField(default=False, verbose_name='WEEE Small Appliance'),
        ),
        migrations.AddField(
            model_name='superdatabaserecord',
            name='wet_damp',
            field=models.BooleanField(default=False, verbose_name='Wet/Damp'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='agglomerate_crumbs',
            field=models.BooleanField(default=False, verbose_name='Agglomerate/Crumbs'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='agricultural_chemical_containers',
            field=models.BooleanField(default=False, verbose_name='Agricultural Chemical Containers'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='agricultural_plant_containers',
            field=models.BooleanField(default=False, verbose_name='Agricultural Plant Containers'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='agricultural_source',
            field=models.BooleanField(default=False, verbose_name='Agricultural Source'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='asa',
            field=models.BooleanField(default=False, verbose_name='ASA'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='automotive_battery',
            field=models.BooleanField(default=False, verbose_name='Automotive/Battery'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='automotive_bumper',
            field=models.BooleanField(default=False, verbose_name='Automotive/Bumper'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='automotive_cable',
            field=models.BooleanField(default=False, verbose_name='Automotive/Cable'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='automotive_elv',
            field=models.BooleanField(default=False, verbose_name='Automotive ELV'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='automotive_fuel_tank',
            field=models.BooleanField(default=False, verbose_name='Automotive/Fuel Tank'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='automotive_interior_trim',
            field=models.BooleanField(default=False, verbose_name='Automotive/Interior Trim'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='bottles',
            field=models.BooleanField(default=False, verbose_name='Bottles'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='building_pipe',
            field=models.BooleanField(default=False, verbose_name='Building Pipe'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='clean',
            field=models.BooleanField(default=False, verbose_name='Clean'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='collection_service',
            field=models.BooleanField(default=False, verbose_name='Collection Service'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='commercial_source',
            field=models.BooleanField(default=False, verbose_name='Commercial Source'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='dirty_soiled',
            field=models.BooleanField(default=False, verbose_name='Dirty/Soiled'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='drum_crate_box',
            field=models.BooleanField(default=False, verbose_name='Drum/Crate/Box'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='eps_packaging',
            field=models.BooleanField(default=False, verbose_name='EPS Packaging'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='feedstock_chemical_recycling',
            field=models.BooleanField(default=False, verbose_name='Feedstock/Chemical Recycling'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='filled_compounds',
            field=models.BooleanField(default=False, verbose_name='Filled Compounds'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='finished_products',
            field=models.CharField(blank=True, max_length=255, verbose_name='Finished Products'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='food_grade',
            field=models.BooleanField(default=False, verbose_name='Food Grade'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='food_trays_containers',
            field=models.BooleanField(default=False, verbose_name='Food Trays Containers'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='hazardous',
            field=models.BooleanField(default=False, verbose_name='Hazardous'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='house_municipal_source',
            field=models.BooleanField(default=False, verbose_name='House Municipal Source'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='industrial_source',
            field=models.BooleanField(default=False, verbose_name='Industrial Source'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='main_source',
            field=models.TextField(blank=True, verbose_name='Main Source'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='maximum_capacity',
            field=models.CharField(blank=True, max_length=255, verbose_name='Maximum Capacity'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='metal_detection',
            field=models.BooleanField(default=False, verbose_name='Metal Detection'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='minimum_volume_waste_accepted',
            field=models.CharField(blank=True, max_length=255, verbose_name='Minimum Volume Waste Accepted'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='number_of_recycling_lines',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Recycling Lines'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='other_automotive',
            field=models.CharField(blank=True, max_length=255, verbose_name='Other Automotive'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='other_building',
            field=models.CharField(blank=True, max_length=255, verbose_name='Other Building'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='other_contaminations',
            field=models.CharField(blank=True, max_length=255, verbose_name='Other Contaminations'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='other_markets',
            field=models.TextField(blank=True, verbose_name='Other Markets'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='other_mechanical_process',
            field=models.TextField(blank=True, verbose_name='Other Mechanical Process'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='other_moulded_parts',
            field=models.BooleanField(default=False, verbose_name='Other Moulded Parts'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='other_packaging',
            field=models.CharField(blank=True, max_length=255, verbose_name='Other Packaging'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='other_weee',
            field=models.CharField(blank=True, max_length=255, verbose_name='Other WEEE'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='packaging_film',
            field=models.BooleanField(default=False, verbose_name='Packaging Film'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='pelletising',
            field=models.BooleanField(default=False, verbose_name='Pelletising'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='pellets',
            field=models.BooleanField(default=False, verbose_name='Pellets'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='prewash',
            field=models.BooleanField(default=False, verbose_name='Prewash'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='pur',
            field=models.BooleanField(default=False, verbose_name='PUR'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='pvc_building_profiles',
            field=models.BooleanField(default=False, verbose_name='PVC Building Profiles'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='recycle_non_elv',
            field=models.BooleanField(default=False, verbose_name='Recycle Non ELV'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='recycle_non_weee',
            field=models.BooleanField(default=False, verbose_name='Recycle Non WEEE'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='regrind',
            field=models.BooleanField(default=False, verbose_name='Regrind'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='separation',
            field=models.BooleanField(default=False, verbose_name='Separation'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='single_screws',
            field=models.IntegerField(blank=True, null=True, verbose_name='Single Screws'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='size_reduction',
            field=models.BooleanField(default=False, verbose_name='Size Reduction'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='sorting',
            field=models.BooleanField(default=False, verbose_name='Sorting'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='textile_fibre_filament',
            field=models.BooleanField(default=False, verbose_name='Textile/Fibre Filament'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='textile_non_woven',
            field=models.BooleanField(default=False, verbose_name='Textile/Non Woven'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='textile_woven',
            field=models.BooleanField(default=False, verbose_name='Textile/Woven'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='toys_sports_leisure',
            field=models.BooleanField(default=False, verbose_name='Toys/Sports/Leisure'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='twin_screws',
            field=models.IntegerField(blank=True, null=True, verbose_name='Twin Screws'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='volume_of_recycled_product',
            field=models.CharField(blank=True, max_length=255, verbose_name='Volume of Recycled Product'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='washing',
            field=models.BooleanField(default=False, verbose_name='Washing'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='weee',
            field=models.BooleanField(default=False, verbose_name='WEEE'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='weee_it_electronic',
            field=models.BooleanField(default=False, verbose_name='WEEE IT Electronic'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='weee_large_appliance',
            field=models.BooleanField(default=False, verbose_name='WEEE Large Appliance'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='weee_small_appliance',
            field=models.BooleanField(default=False, verbose_name='WEEE Small Appliance'),
        ),
        migrations.AddField(
            model_name='unverifiedsite',
            name='wet_damp',
            field=models.BooleanField(default=False, verbose_name='Wet/Damp'),
        ),
        migrations.AlterField(
            model_name='datacollectionproject',
            name='category',
            field=models.CharField(choices=[('INJECTION', 'Injection Moulders'), ('BLOW', 'Blow Moulders'), ('ROTO', 'Roto Moulders'), ('PE_FILM', 'PE Film Extruders'), ('SHEET', 'Sheet Extruders'), ('PIPE', 'Pipe Extruders'), ('TUBE_HOSE', 'Tube & Hose Extruders'), ('PROFILE', 'Profile Extruders'), ('CABLE', 'Cable Extruders'), ('COMPOUNDER', 'Compounders'), ('RECYCLER', 'Recyclers')], help_text='Primary category for this project', max_length=50),
        ),
        migrations.AlterField(
            model_name='productionsite',
            name='category',
            field=models.CharField(choices=[('INJECTION', 'Injection Moulders'), ('BLOW', 'Blow Moulders'), ('ROTO', 'Roto Moulders'), ('PE_FILM', 'PE Film Extruders'), ('SHEET', 'Sheet Extruders'), ('PIPE', 'Pipe Extruders'), ('TUBE_HOSE', 'Tube & Hose Extruders'), ('PROFILE', 'Profile Extruders'), ('CABLE', 'Cable Extruders'), ('COMPOUNDER', 'Compounders'), ('RECYCLER', 'Recyclers')], help_text='Production category', max_length=20),
        ),
        migrations.AlterField(
            model_name='superdatabaserecord',
            name='category',
            field=models.CharField(choices=[('INJECTION', 'Injection Moulders'), ('BLOW', 'Blow Moulders'), ('ROTO', 'Roto Moulders'), ('PE_FILM', 'PE Film Extruders'), ('SHEET', 'Sheet Extruders'), ('PIPE', 'Pipe Extruders'), ('TUBE_HOSE', 'Tube & Hose Extruders'), ('PROFILE', 'Profile Extruders'), ('CABLE', 'Cable Extruders'), ('COMPOUNDER', 'Compounders'), ('RECYCLER', 'Recyclers')], help_text='The main category of this company.', max_length=20),
        ),
        migrations.AlterField(
            model_name='unverifiedsite',
            name='category',
            field=models.CharField(choices=[('INJECTION', 'Injection Moulders'), ('BLOW', 'Blow Moulders'), ('ROTO', 'Roto Moulders'), ('PE_FILM', 'PE Film Extruders'), ('SHEET', 'Sheet Extruders'), ('PIPE', 'Pipe Extruders'), ('TUBE_HOSE', 'Tube & Hose Extruders'), ('PROFILE', 'Profile Extruders'), ('CABLE', 'Cable Extruders'), ('COMPOUNDER', 'Compounders'), ('RECYCLER', 'Recyclers')], help_text='The main category of this company.', max_length=20),
        ),
    ]
