# Generated by Django 5.2.7 on 2025-12-16 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0024_productionsiteversion_agglomerate_crumbs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpArticleFeedback',
            fields=[
                ('feedback_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('article_id', models.CharField(help_text="Identifier for the help article (e.g., 'welcome', 'viewing-reports')", max_length=100)),
                ('is_helpful', models.BooleanField(help_text='Whether the user found the article helpful')),
                ('comment', models.TextField(blank=True, help_text='Optional additional feedback comment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who submitted the feedback', on_delete=django.db.models.deletion.CASCADE, related_name='help_article_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Help Article Feedback',
                'verbose_name_plural': 'Help Article Feedbacks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'article_id'], name='reports_hel_user_id_043279_idx'), models.Index(fields=['is_helpful'], name='reports_hel_is_help_fe8210_idx'), models.Index(fields=['-created_at'], name='reports_hel_created_06ce51_idx')],
                'unique_together': {('user', 'article_id')},
            },
        ),
    ]
