# Generated by Django 5.2.7 on 2025-12-16 14:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_helparticlefeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFeedback',
            fields=[
                ('feedback_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], help_text='Rating from 1 (poor) to 5 (excellent)')),
                ('comment', models.TextField(blank=True, help_text='Optional additional feedback comment', null=True)),
                ('data_quality_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating for data quality', null=True)),
                ('data_completeness_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating for data completeness', null=True)),
                ('ease_of_use_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating for ease of use', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(help_text='Report this feedback is for', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='reports.customreport')),
                ('user', models.ForeignKey(help_text='User who submitted the feedback', on_delete=django.db.models.deletion.CASCADE, related_name='report_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Feedback',
                'verbose_name_plural': 'Report Feedbacks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'report'], name='reports_rep_user_id_02f64a_idx'), models.Index(fields=['rating'], name='reports_rep_rating_7b51e3_idx'), models.Index(fields=['-created_at'], name='reports_rep_created_cb9616_idx'), models.Index(fields=['report', '-created_at'], name='reports_rep_report__396d93_idx')],
                'unique_together': {('user', 'report')},
            },
        ),
    ]
