# Generated by Django 5.2.7 on 2025-12-17 07:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0026_reportfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_id', models.IntegerField(blank=True, help_text='ID of the SuperdatabaseRecord this note is attached to', null=True)),
                ('company_name', models.CharField(blank=True, help_text='Company name for quick display', max_length=255, null=True)),
                ('title', models.CharField(blank=True, help_text='Optional title for the note', max_length=200, null=True)),
                ('content', models.TextField(help_text='Note content')),
                ('color', models.CharField(choices=[('yellow', 'Yellow'), ('blue', 'Blue'), ('green', 'Green'), ('pink', 'Pink'), ('purple', 'Purple'), ('orange', 'Orange')], default='yellow', max_length=20)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned notes appear at the top')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_notes', to='reports.customreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Note',
                'verbose_name_plural': 'Client Notes',
                'ordering': ['-is_pinned', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'report'], name='reports_cli_user_id_7191e1_idx'), models.Index(fields=['user', 'report', 'record_id'], name='reports_cli_user_id_260b5c_idx'), models.Index(fields=['-is_pinned', '-updated_at'], name='reports_cli_is_pinn_ff83e4_idx')],
            },
        ),
    ]
