# Generated by Django 5.2.7 on 2025-12-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0027_clientnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientnote',
            name='record_id',
            field=models.CharField(blank=True, help_text='ID of the SuperdatabaseRecord this note is attached to (can be UUID or integer)', max_length=50, null=True),
        ),
    ]
