# Generated by Django 5.2.7 on 2025-12-17 10:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0028_alter_clientnote_record_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Collection name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('purple', 'Purple'), ('green', 'Green'), ('red', 'Red'), ('orange', 'Orange'), ('pink', 'Pink'), ('teal', 'Teal'), ('indigo', 'Indigo')], default='blue', max_length=20)),
                ('icon', models.CharField(choices=[('folder', 'Folder'), ('star', 'Star'), ('bookmark', 'Bookmark'), ('heart', 'Heart'), ('briefcase', 'Briefcase'), ('target', 'Target'), ('flag', 'Flag'), ('tag', 'Tag')], default='folder', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Collection',
                'verbose_name_plural': 'Company Collections',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_id', models.CharField(help_text='ID of the company record', max_length=50)),
                ('company_name', models.CharField(help_text='Company name for display purposes', max_length=255)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, help_text='Optional note about why this company was added', null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='reports.customreport')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports.companycollection')),
            ],
            options={
                'verbose_name': 'Collection Item',
                'verbose_name_plural': 'Collection Items',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_id', models.CharField(help_text='ID of the company record', max_length=50)),
                ('company_name', models.CharField(help_text='Company name for display purposes', max_length=255)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='reports.customreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Company',
                'verbose_name_plural': 'Favorite Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PinnedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_by', to='reports.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pinned Report',
                'verbose_name_plural': 'Pinned Reports',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='companycollection',
            index=models.Index(fields=['user', 'name'], name='reports_com_user_id_8fd61c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collectionitem',
            unique_together={('collection', 'report', 'record_id')},
        ),
        migrations.AddIndex(
            model_name='favoritecompany',
            index=models.Index(fields=['user', 'report'], name='reports_fav_user_id_efa095_idx'),
        ),
        migrations.AddIndex(
            model_name='favoritecompany',
            index=models.Index(fields=['user', '-created_at'], name='reports_fav_user_id_026d1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritecompany',
            unique_together={('user', 'report', 'record_id')},
        ),
        migrations.AlterUniqueTogether(
            name='pinnedreport',
            unique_together={('user', 'subscription')},
        ),
    ]
