# Generated by Django 5.2.7 on 2025-12-24 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0030_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='company',
            name='rpt_company_stat_cntry_idx',
        ),
        migrations.RemoveIndex(
            model_name='productionsiteversion',
            name='rpt_psv_curr_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='productionsiteversion',
            name='rpt_psv_is_current_idx',
        ),
    ]
