# Generated by Django 5.2.7 on 2025-10-28 11:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('summary', models.CharField(blank=True, help_text='Short summary for preview', max_length=300)),
                ('announcement_type', models.CharField(choices=[('general', 'General'), ('maintenance', 'Maintenance'), ('feature', 'New Feature'), ('update', 'Update'), ('event', 'Event'), ('alert', 'Alert')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('expired', 'Expired'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('clients', 'Clients Only'), ('staff', 'Staff Only'), ('superadmin', 'Superadmin Only'), ('custom', 'Custom Selection')], default='all', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, help_text='Leave blank for no expiration', null=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin to top of announcements')),
                ('show_popup', models.BooleanField(default=False, help_text='Show as popup on user login')),
                ('require_acknowledgment', models.BooleanField(default=False, help_text='User must acknowledge reading')),
                ('icon', models.CharField(blank=True, help_text='Icon name from lucide-react', max_length=50)),
                ('color_scheme', models.CharField(default='blue', help_text='Color theme for the announcement', max_length=50)),
                ('action_button_text', models.CharField(blank=True, help_text="e.g., 'Learn More'", max_length=50)),
                ('action_button_url', models.URLField(blank=True, help_text='External or internal URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('specific_users', models.ManyToManyField(blank=True, related_name='targeted_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='announcements/attachments/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='Size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='announcements.announcement')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_views', to='announcements.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['-start_date', 'status'], name='announcemen_start_d_c14e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['target_audience', 'status'], name='announcemen_target__089fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementview',
            index=models.Index(fields=['announcement', 'user'], name='announcemen_announc_59a72f_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementview',
            index=models.Index(fields=['user', '-viewed_at'], name='announcemen_user_id_d5da33_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='announcementview',
            unique_together={('announcement', 'user')},
        ),
    ]
