# Generated by Django 5.2.7 on 2025-10-29 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementview',
            name='hidden',
            field=models.BooleanField(default=False, help_text='User has dismissed this announcement'),
        ),
        migrations.AddIndex(
            model_name='announcementview',
            index=models.Index(fields=['user', 'hidden'], name='announcemen_user_id_a7a906_idx'),
        ),
    ]
