# Generated by Django 5.2.7 on 2025-12-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcementview_hidden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All Users'), ('clients', 'Clients Only'), ('staff', 'Staff Only'), ('superadmin', 'Superadmin Only'), ('data_collectors', 'Data Collectors Only'), ('custom', 'Custom Selection')], default='all', max_length=20),
        ),
    ]
