# Generated by Django 5.2.7 on 2025-11-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_site_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('report', 'New Report'), ('subscription', 'Subscription'), ('message', 'Message'), ('announcement', 'Announcement'), ('payment', 'Payment'), ('system', 'System'), ('calling', 'Calling Workflow')], max_length=20),
        ),
    ]
